---
repos:
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.43.0
      hooks:
          - id: markdownlint
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3 # or other specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/codespell-project/codespell
      rev: v2.3.0
      hooks:
          - id: codespell
            name: codespell
            description: Checks for common misspellings in text files.
            types: [text]